---
- name: Update the package list
  apt: update_cache=yes

- name: Configure for automatic security updates
  copy: src=apt-auto-upgrades dest=/etc/apt/apt.conf.d/20auto-upgrades

- name: Install automatic security updates
  command: /usr/bin/unattended-upgrade

- name: Install base system packages
  apt: name={{item}} state=installed
  with_items:
    - build-essential
    - python-setuptools
    - python-pip
    - python-apt
    - python-dev
    - python-pycurl
    - python-software-properties