---
- name: set locale to {{locale}}
  command: /usr/sbin/update-locale LANG={{locale}} LC_ALL={{locale}}

- name: ensure postres is installed
  apt: name={{item}} state=installed update-cache=yes
  with_items:
    - postgresql
    - postgresql-contrib
    - python-psycopg2

- name: create database
  sudo_user: postgres
  postgresql_db: name={{db_name}} owner={{db_user}} lc_ctype={{locale}} lc_collate={{locale}}

- name: create the postgre user
  sudo_user: postgres
  postgresql_user: db={{db_name}} name={{db_user}} password={{db_password}} priv=ALL role_attr_flags=CREATEDB

- name: Setup postgres to listen on other interfaces
  lineinfile: dest=/etc/postgresql/9.3/main/postgresql.conf line="listen_addresses='*'"
  notify:
    - restart postgres