---
- name: create directory for code
  file: dest={{project_path}} mode=0777 owner={{username}} group={{groupname}} recurse=yes state=directory

- name: install required base packages
  apt: pkg={{item}}
  with_items:
    - libpq-dev
    - python-django
    - postgresql-client
    - python-virtualenv

- name: install python requirements
  sudo: no
  pip: requirements={{requirements_path}} virtualenv={{python_path}}

- name: Set up the application
  django_manage: app_path={{ project_path }} command=setup virtualenv={{ python_path }}
  environment: env_vars

  # todo: set up django application
  # todo: django setup command (pip install, migration, starting data)


#- apt: name=python-software-properties
#- apt_repository: repo='ppa:chris-lea/node.js'
#- apt: name=nodejs update_cache=yes
#
#- npm: name={{ item }} global=yes
#  with_items:
#    - coffee-script
#    - karma
#    - karma-cli
#    - grunt
#    - grunt-cli
#    - phantomjs
#
#- npm: path={{ grunt_root_folder }} state=present
#  when: grunt_root_folder is defined